# Generated by Django 2.0.7 on 2018-11-11 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export_ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportreport',
            options={'verbose_name': 'Export', 'verbose_name_plural': 'Exports'},
        ),
        migrations.AlterField(
            model_name='exportreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL),
        ),
    ]
