# Generated by Django 2.1.5 on 2019-03-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Genre name', max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='test', help_text='Slug for urls', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation date'),
        ),
    ]
