# Generated by Django 2.1.5 on 2019-03-03 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20190302_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='mbid',
            field=models.CharField(db_index=True, max_length=36, unique=True, validators=[django.core.validators.MinLengthValidator(36), django.core.validators.MaxLengthValidator(36)]),
        ),
    ]
