# Generated by Django 2.1.5 on 2020-07-17 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=-1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Album')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=400, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordered', models.BooleanField(default=False, verbose_name='Ordered list (top)')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
                ('albums', models.ManyToManyField(related_name='lists', through='lists.ListItem', to='albums.Album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'ordering': ['-vote_score'],
            },
        ),
        migrations.AddField(
            model_name='listitem',
            name='item_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.ListObj'),
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('item_list', 'album')},
        ),
    ]
