# Generated by Django 2.1.5 on 2019-02-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('lists', '0002_auto_20190218_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('item_list', 'album')},
        ),
    ]
