# Generated by Django 2.1.5 on 2019-03-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190218_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listobj',
            options={'ordering': ['-vote_score'], 'verbose_name': 'list', 'verbose_name_plural': 'lists'},
        ),
    ]
