# Generated by Django 2.1.5 on 2021-09-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='media_cover',
            field=models.ImageField(null=True, upload_to='album_covers'),
        ),
    ]
