# Generated by Django 2.1.5 on 2022-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_media_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='youtube_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
