# Generated by Django 2.1.5 on 2022-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_add_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('SI', 'Single'), ('LP', 'LP'), ('EP', 'EP'), ('LI', 'Live'), ('CP', 'Compilation'), ('RE', 'Remix'), ('UK', 'Unknown')], default='LP', max_length=2),
        ),
    ]
