# Generated by Django 4.0.4 on 2022-04-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20220428_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='users_interested',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
