# Generated by Django 4.0.4 on 2022-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_album_users_interested_delete_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
