# Generated by Django 4.0.4 on 2022-05-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_remove_album_spotify_link_remove_album_youtube_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumlinks',
            name='deezer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
