# Generated by Django 4.0.4 on 2023-09-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_alter_album_title_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
