# Generated by Django 4.0.4 on 2023-09-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_artist_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('pk',), 'verbose_name': 'Album'},
        ),
    ]
