# Generated by Django 2.0.7 on 2018-07-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Critique')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date publication')),
                ('date_last_change', models.DateField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
