# Generated by Django 2.0.7 on 2018-07-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        ('star_ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='star_ratings.UserRating'),
        ),
    ]
