# Generated by Django 4.0.4 on 2022-05-13 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('bug', 'Report a bug'), ('suggestion', 'Suggest new feature'), ('signal', 'Signal inappropriate behavior'), ('data', 'Report album / genre / artist not present on the site'), ('other', 'Something else')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='AnonymousFeedback',
        ),
    ]
