# Generated by Django 4.0.4 on 2022-05-13 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Message'),
        ),
    ]
