# Generated by Django 2.0.7 on 2018-07-14 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover', models.CharField(max_length=100, null=True)),
                ('album_type', models.CharField(choices=[('SI', 'Single'), ('LP', 'Album'), ('EP', 'EP'), ('LI', 'Live'), ('CP', 'Compilation'), ('RE', 'Remix')], default='LP', max_length=2)),
            ],
            options={
                'verbose_name': 'Album',
            },
        ),
        migrations.CreateModel(
            name='AlbumGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_genre', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('albums', models.ManyToManyField(blank=True, related_name='artists', to='albums.Album')),
            ],
            options={
                'verbose_name': 'Artiste',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du genre', max_length=200, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', help_text='Description du genre', null=True, verbose_name='Description')),
                ('slug', models.SlugField(help_text='Court nom descriptif pour les urls', max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.Genre')),
            ],
            options={
                'verbose_name_plural': 'genres',
                'ordering': ('name',),
                'verbose_name': 'genre',
            },
        ),
        migrations.AddField(
            model_name='albumgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Genre'),
        ),
        migrations.AddField(
            model_name='albumgenre',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='albums', through='albums.AlbumGenre', to='albums.Genre'),
        ),
    ]
