# Generated by Django 2.1.5 on 2020-07-17 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bug', 'Reporter un bug'), ('suggestion', 'Faire une suggestion'), ('signal', 'Signaler un comportement'), ('album', 'Rapporter un album non présent sur le site')], max_length=100, verbose_name='Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bug', 'Reporter un bug'), ('suggestion', 'Faire une suggestion'), ('signal', 'Signaler un comportement'), ('album', 'Rapporter un album non présent sur le site')], max_length=100, verbose_name='Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
    ]
