# Generated by Django 2.1.5 on 2019-02-04 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'discussion',
                'verbose_name_plural': 'discussions',
                'ordering': ['-modified'],
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['modified'], name='discussions_modifie_3b55c1_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['created'], name='discussions_created_ad9381_idx'),
        ),
    ]
