# Generated by Django 2.1.5 on 2019-03-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20190302_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last edit'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
    ]
