# Generated by Django 2.0.7 on 2018-07-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluentComment',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Comments',
                'managed': False,
                'proxy': True,
                'verbose_name': 'Comment',
            },
            bases=('django_comments.comment',),
        ),
    ]
