# Generated by Django 2.0.7 on 2018-09-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created'], 'verbose_name': 'Discussion', 'verbose_name_plural': 'Discussions'},
        ),
    ]
