# Generated by Django 2.0.7 on 2018-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20180902_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
