# Generated by Django 2.0.7 on 2018-09-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20180903_1225'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['created'], name='discussions_created_ad9381_idx'),
        ),
    ]
