# Generated by Django 2.0.7 on 2018-07-14 11:10

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=account.models.user_avatar_path, verbose_name='Avatar')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('description', models.TextField(blank=True, default='', max_length=400, verbose_name='Description')),
                ('sex', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('N', 'Anonyme')], default='N', max_length=1, verbose_name='Sexe')),
                ('display_birth', models.BooleanField(default=True, verbose_name='Afficher naissance')),
                ('display_name', models.BooleanField(default=False, verbose_name='Afficher nom')),
                ('display_sex', models.BooleanField(default=False, verbose_name='Afficher sexe')),
                ('top_albums', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.ItemList')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
