# Generated by Django 2.1.5 on 2020-07-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('date_last_change', models.DateTimeField(auto_now=True, verbose_name='Last edit')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
