# Generated by Django 2.1.5 on 2020-12-12 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20201212_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_read',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last read'),
            preserve_default=False,
        ),
    ]
