# Generated by Django 2.1.5 on 2020-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_membership_last_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_edit',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last edit'),
        ),
    ]
