# Generated by Django 2.1.5 on 2020-12-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
