# Generated by Django 2.1.5 on 2020-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_membership_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='unread',
            field=models.BooleanField(default=True, verbose_name='Unread'),
        ),
    ]
