# Generated by Django 2.1.5 on 2020-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_auto_20201212_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='Last edit'),
        ),
    ]
