# Generated by Django 2.1.5 on 2020-12-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_membership_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='read_by_all',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='unread_by',
        ),
    ]
