# Generated by Django 2.1.5 on 2020-07-17 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=user_profile.models.user_avatar_path, verbose_name='Avatar')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('description', models.TextField(blank=True, default='', max_length=400, verbose_name='Description')),
                ('sex', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('N', 'Anonyme')], default='N', max_length=1, verbose_name='Sex')),
                ('display_birth', models.BooleanField(default=False, verbose_name='Display birth')),
                ('display_name', models.BooleanField(default=False, verbose_name='Display name')),
                ('display_sex', models.BooleanField(default=False, verbose_name='Display gender')),
                ('last_activity', models.DateTimeField(auto_now_add=True, verbose_name='Last activity')),
                ('top_albums', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lists.ListObj')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
